### ISSUE TITLE
Tighten up the definition of Fair Source

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#21]
So this is a bit last-minute, with the launch coming up next Tuesday, but after much vigorous debate internally at Sentry, we have decided that we want to move forward with tightening up the definition of Fair Source. The basic reason is to clarify our positioning relative to other alternatives in the market: Open Core, closed-source, source-available, and of course FOSS. As we wrestled with how to message Fair Source in our announcement blog post and expected media conversations, we especially struggled with the "tiers" chart on the licenses page:

<img width="525" alt="tiers" src="https://github.com/user-attachments/assets/8a5f8aa8-d423-412f-96e1-79470b757fa3">

This is really complex. We had trouble explaining it succinctly to ourselves. If we're confused, what hope does anyone else have? If we stand for everything, we stand for nothing. Open Core / COSS in particular is something we expect to be compared with and asked how we differ from. With the status quo we don't have a clear answer, and we need one.

### Back to Basics

We stepped back and looked at our original goal: to remove objections to the approaches companies like Sentry are taking to software sharing, to maximize developers’ ability to adopt our software, while maintaining commercial protections to enable sustainability.

One key thing stood out that really differentiates that point of view from other approaches: [delayed Open Source publication](https://opensource.org/dosp) (DOSP). It greatly minimizes the rug pull objection, as the terms are clear up front. It genuinely does create more Open Source in the world as the license conversion to FOSS is absolute. And it gives our companies a head start on commercialization that has been demonstrated to be effective through years of experience at this point.

Therefore, the best solution we came up with to the marketing / messaging challenge with Fair Source is to **commit to DOSP as a defining characteristic**. Not only does DOSP clearly differentiate us from both Open Core and FOSS, but it also gives us a clear through-line with [BUSL](https://mariadb.com/bsl-faq-mariadb/), the [DOSP](https://opensource.org/dosp) paper (published by OSI), [FSL](https://fsl.software/), [FCL](https://fcl.dev/), and [beyond](https://www.batteriesincl.com/LICENSE-1.0). We can tell a compelling story.

### Defining Fair Source

Even if we make DOSP necessary, it is clearly not sufficient. What is the litmus test for Fair Source access _prior_ to FOSS conversion? If a product is fully closed-source until the DOSP date then clearly that is not Fair Source. Here is the definition we propose moving forward with for launch:

> Fair Source is an approach to software licensing that offers:
>
> - minimal usage restrictions to protect the producer’s business model; and
> - [delayed Open Source publication](https://opensource.org/dosp).
>
> Through Fair Source, companies can engage developers by providing meaningful access, while preserving their business model and product roadmap ownership.

There is some subjective variation within both of these criteria, especially the concept of “minimal non-compete restrictions.” While we think the FSL is the best version of this, we also recognize that not every piece of software can package itself as a cloud service. But while it’s subjective, we think the intent is stated well enough. We expect patterns to emerge over time as companies and the wider developer community explore the Fair Source solution space together.

What this means practically is that tiers (3) and (4) are going away. We'll fully rework the licenses page and the rest of the website copy to reflect this change. It does mean that we won't be able to bring everyone along with us for the Fair Source ride, but, again, we need to bring a differentiated solution to market in order for Fair Source to have a lasting impact.

**Comment by chadwhitacre** [comment]
Sorry team, accidentally posted a draft of this while updating to the final. Edited now.

**Comment by ezekg** [comment]
I agree that the tiered system is convoluted. I was actually looking at it today thinking the same thing. In my head canon, I thought of Fair Source more like a gradient and less like a tiered system. What I mean by that is that you have Open Source on the left, and then source-available on the right. With DOSP, under FSL, you're very far left; under FCL, you're a little further right than FSL but still far left; BUSL is all over the place because it's effectively a unique DOSP license each time. Under ELv2 or SUL, you're leaning more towards the right without DOSP. But in all cases, you abide by the 4 freedoms of Fair Source, so even if you're far right, that you can still immediately convey those user freedoms by using the Fair Source term. The beauty of this is that Fair Source provides a new term for all the various projects and licenses that are close to Open Source, in terms of user freedoms, but not quite Open Source. Changing the definition to require DOSP changes that dynamic and alienates a lot of authors already using SSPL, ELv2, SUL, among others from the benefits of immediately using a new term that conveys the user freedoms their projects already offer yet unable to convey with the "source-available" term they're told to use.

With that said, maybe DOSP as a defining characteristic of Fair Source is a good thing. It's still a gradient, but one that's even closer to Open Source as a whole, albeit with a smaller pool of projects that can use the term. But if we can push the authors using ELv2 to FCL, and those using SSPL/SUL to FSL, and the rest to other/new DOSP licenses, we provide a clear path to building sustainable businesses on top of permissive licenses while eventually contributing to Open Source. And we can all agree that's good..

My big concern here is that those licenses that are already close to Open Source but not DOSP are still forced to either settle for "source-available" and fight to convey their user freedoms, or open-wash to convey them right away. Most will choose the latter. Maybe the negative effects of that will eventually push them to Fair Source and DOSP, but maybe not.

With all that said, I'm okay with this change. It doesn't fit my head canon, and it's not my ideal outcome, but I can see how it can simplify the term and grow the DOSP license pool.

If there a lurkers here that use ELv2, SUL, etc. and disagree, and don't want to go DOSP, please speak up.

**Comment by chadwhitacre** [comment]
Lots of alignment there, @ezekg. 

> It's still a gradient, but one that's even closer to Open Source as a whole

Exactly.

> albeit with a smaller pool of projects that can immediately use the term.

Yes, that's the trade-off. Focus and clarity always come at a cost, but are necessary for success.

> Right now, it's been pretty silent from that side (excluding myself).

This is definitely part of the equation. I reached out privately to some of the major players associated with Tier 3 and 4 licenses. There was really no interest in participating in Fair Source. A vibe I got is that folks would rather find a path to legitimacy with OSI for a copyleft-style license that offers more protection against hyperscalers than current offerings. More power to them.

The one exception of course is n8n, authors of [SUL](https://docs.n8n.io/faircode-license/#what-is-the-sustainable-use-license) and stewards of [Fair-code](https://faircode.io/) (cf. #10). They have not been active here over the past months, but we have reconnected privately in the past weeks, and I've shared this direction with them (#20 came out of that private thread, tbh). It's a tough call, but I think we do best by Fair Source to clearly differentiate ourselves in the market by drawing a bright line at DOSP, and then within that explore the solution space for different monetization models (SaaS, self-hosted, etc.), as you're doing with [FCL](https://fcl.dev/) and as we now have also have @elliottneilclark doing with [BIL](https://www.batteriesincl.com/LICENSE-1.0).

**Comment by ezekg** [comment]
> I think we do best by Fair Source to clearly differentiate ourselves in the market by drawing a bright line at DOSP, and then within that explore the solution space for different monetization models (SaaS, self-hosted, etc.), as you're doing with FCL and as we now have also have @elliottneilclark doing with BIL.

I agree. I was hoping the authors using SUL and ELv2 would chime in more, but alas.

Like I said, I'm okay with this change. It makes sense to differentiate.

**Comment by chadwhitacre** [comment]
> Are we still going to have the 4 freedoms?

I've gotten some feedback that too closely echoing Free Software's four freedoms invites rancor from advocates by highlighting what's missing. One suggestion is that "right to repair" language is a better anchor. From the standpoint of deciding which companies we're going to accept for fair.io/companies and which licenses we're going to accept for fair.io/licenses, are these two criteria enough to work with?

1. delayed Open Source publication
2. minimal usage restrictions to protect the producer’s business model

(1) is bright. (2) is pretty broad but is intended to be. FSF's four freedoms are hidden under "usage," what we consider acceptable modifications under "minimal restrictions." Can you imagine successful conversations about whether something is Fair Source or not by applying these two criteria?

**Comment by ezekg** [comment]
I feel like this assumes the user already knows the 4 freedoms of the OSD, because otherwise this conveys nothing except DOSP, which is antithetical to what the term needs to be. Like you originally said, a closed-source project obviously wouldn't be considered Fair Source, but I think that needs to be obvious and not left up for interpretation. I understand wanting to "see what happens", but not requiring that Fair Source licenses are publicly available to read and modify will also invite rancor, and worse, confusion in what the term actually other than DOSP. Preferably, I'd say the unrestricted right to read, with minimally restricted rights to use, modify, and redistribute are essential in communicating that Fair Source is very close to Open Source. There can be variance, and that's fine, as long as the restrictions are minimal.

As it currently stands with your 2-point definition, you can't immediately communicate that Fair Source is close to Open Source, in terms of freedoms, without discussing a particular license and the OSD itself. And that'd be to the detriment of the initiative, imo. And if we're now requiring and encouraging DOSP, I don't see any reason why we'd want to stray further away from Open Source than the original 4 freedoms we had defined (which were based on the OSD).

I'd suggest something like:

> Fair Source projects:
>
> 1. are delayed Open Source publication;
> 2. are publicly available to read; and
> 4. allow use, modification, and redistribution with minimal restrictions to protect the producer’s business model.

This leaves room for minimal restrictions on top of use, modification, and redistribution _for business purposes_, but still makes them required. I feel like this leaves much less room for ambiguity, and immediately makes it clear that Fair Source is all about user freedom and developer sustainability, not just restrictions for the sake of restriction.

wdyt?

**Comment by chadwhitacre** [comment]
I can work with that. We might reorder (1) to the end but that's minor.

Let me see what @dcramer @benvinegar @GavinZee think.

**Comment by elliottneilclark** [comment]
First, thank you for doing this. I struggled internally with passing good or bad judgments about how the licenses work for others. So, focusing on the strengths of these licenses is perfect. Don't try to be everything to everyone. Be the best of our strengths.

> minimal usage restrictions to protect the producer’s business model

I've had good conversations when I discuss aligning incentives for the software producer/maintainer. These licenses allow the people/teams/companies building the software to be paid for maintenance and new features while giving enough freedom to ensure that stagnation or price gouging will be met with migrations to the open-source versions.

**Comment by ezekg** [comment]
Here's how I'm going to describe Fair Source in [my blog post](https://next.keygen.sh/blog/keygen-is-now-fair-source/):

> Fair Source projects are DOSP. They are publicly available to read and provide the freedom to use, modify, and redistribute, with minimal restrictions to protect the producer's business model. Fair Source values both user freedom and developer sustainability.

lmkyt

**Comment by elliottneilclark** [comment]
That's very well said. I like it.

**Comment by chadwhitacre** [comment]
Here's the revised relevant section in [Sentry's post](https://docs.google.com/document/d/1yJn6r0Vgg3q2FNAKHwMrGzcBxQZLFH9wOPY0xbZZ4ic/edit?usp=sharing):

> ### Defining Fair Source
> 
> Fair Source is software that:
> 
> 1. is publicly available to read;
> 2. allows use, modification, and redistribution with minimal restrictions to protect the producer’s business model; and
> 3. undergoes delayed Open Source publication (DOSP).
> 
> The intention is for the first point to be a bright line, and to invite exploration within the second. In addition to Sentry’s [Functional Source License](https://fsl.software/) (FSL), Fair Source also [recognizes](http://fair.io/licenses) the new [Fair Core License](https://fcl.dev/) (FCL) from Keygen and MariaDB’s venerable [Business Source License](https://mariadb.com/bsl-faq-mariadb/) (BSL or BUSL) as fitting the [Fair Source Definition](https://fair.io/definition). We expect further licenses to emerge as companies apply Fair Source to their particular business model. Fair Source runs on GitHub, and the [README](https://github.com/fairsource/fair.io) is where we document governance and our processes for recognizing new licenses and company adoption.
> 
> The third point is also intended as a bright line, and a key differentiator of Fair Source from [Open Core](https://opensource.org/blog/opencore) and other approaches. [Delayed Open Source publication](https://opensource.org/dosp) (DOSP) is a concept [established by the Open Source Initiative](https://opensource.org/blog/a-historic-view-of-the-practice-to-delay-releasing-open-source-software-osis-report) (OSI). DOSP ensures that if a Fair Source company goes out of business, or takes their software in an undesired direction, the community or another company can pick up and move forward. Major forks are, of course, a rare event (though perhaps they are [becoming more common](https://redmonk.com/sogrady/2024/07/16/post-valkey-world/)). Time will tell whether our intuition is right that DOSP provides a meaningful long-term forking benefit while allowing companies and developers to better align on the rules of engagement up front for [single-vendor projects](https://dirkriehle.com/publications/2009-selected/the-commercial-open-source-business-model/).

I'm gonna work on revising website copy.

**Comment by chadwhitacre** [comment]
Returning here from working on the [FAQ](https://new.fair.io/faq/), for "Is Fair Source software safe to use?" I _want_ to say, "Yes. Fair Source licenses are written such that it is difficult to violate them." On the one hand, ensuring that is true would likely require adding this to the definition. On the other, thinking through how our existing crop of licenses fares against, this BUSL is sorta out the window due to its variability (we'll need to vet individual implementations of companies vs. the license itself), but for FSL and FCL I believe this holds true. Moreover, I don't think it's true of [BIL](https://www.batteriesincl.com/LICENSE-1.0), where I find this:

> A Permitted Purpose is use of any single instance of the Software on a cluster of up to 3 nodes, where a “node” is any network host in a container system, whether physical, virtual, or para-virtualized.

This puts a burden on the user to carefully read the license and self-monitor their usage of the software. This is in contrast to FSL and FCL where a user who does not read the license is highly unlikely to violate it in the normal course of using the software. One does not stand up a competing SaaS service or circumvent license key restrictions accidentally.

I think it would greatly aid the growth of Fair Source if we can guarantee that it is safe to run for 99.999% of cases. I don't see that we can accept BIL as it stands and keep that guarantee. Could Batteries Included be written in such way as to determine programmatically if it is being run on a cluster of more than three nodes, and require a license kay if so?

**Comment by chadwhitacre** [comment]
Thanks for jumping in @erwin. I appreciate you sharing these parallels and links. I'm not sure what the concrete suggestion is, though at this point we're a couple days out from launch and are pretty firm in our messaging. Wish us luck! :-)

**Comment by chadwhitacre** [comment]
For the record @sqs isn't involved in Fair Source beyond graciously donating the domain, GitHub org, and X account.

> Fair.io can be broadened to also encourage individual developers to consider Fair Licenses?

If a developer adopts a Fair Source license presumably they are trying to commercialize their product and if they are successful they won't be a one-developer project for long. 😁 You should check out the [Open Source Pledge](https://osspledge.com/) for another effort we have underway (separate from Fair Source) to address the "starving FOSS developer" problem.

**Comment by chadwhitacre** [comment]
Launch is tomorrow! Here is the Fair Source Definition we are moving forward with:

> Fair Source Software (FSS):
> 
> 1. is publicly available to read;
> 1. allows use, modification, and redistribution with minimal restrictions to protect the producer’s business model; and
> 1. undergoes delayed Open Source publication (DOSP).

**Comment by ljharb** [comment]
Is it worth pointing out that the first point is aka “Source Available”?

**Comment by chadwhitacre** [comment]
Source-available does not necessarily mean publicly available to read. It can also mean privately available to read under NDA between one company and another.

**Comment by ljharb** [comment]
Interesting, that is very much not the common definition I’d previously understood.

**Comment by ezekg** [comment]
> Interesting, that is very much not the common definition I’d previously understood.

That's the problem with "source-available" — it has no real definition and it conveys no user freedoms at all, which is why the term has never taken off. That's why we needed a new term that does have a concrete definition and does convey user freedoms.

I don't think referencing source-available in the Fair Source definition would have any positive outcome. It may even cause confusion.
